[placeholders.version]
type = "string"
prompt = "What HAL version to use?"
choices = ["last-release", "git"]
default = "last-release"

[placeholders.rtic]
type = "bool"
prompt = "Is it RTIC-based application?"
default = false

[placeholders.chip]
type = "string"
prompt = "What microcontroller name?"
#choices = ["", ""]
default = "stm32f411ceu6"

[hooks]
#init = [...]
pre = ["pre-script.rhai"]
#post = [...]